channels:
  sources: [ramonaoptics, conda-forge, defaults]
  targets:
    - [ramonaoptics, main]

github:
  user_or_org: hmaarrfk

travis:
  secure:
    BINSTAR_TOKEN: IL4wLtD50tFl/bk4FlKC+adlXv//j23fAQUd6URa8S94Pst+YO4RZmF4/qqcymWUYDh9sUi8gPWhlhuLx4xgLJNAkKa0aLENDRe7R2Bi/elWfHhoK89avUEqn072zSnqzjj4X+0G9dc1mhcEwtAtmfebLGnJxyCAIHQuRLAAoCdkp+3NPOOon+vg1RxTduAsJZMZrH2litEp5lSl8p6/naudmNnVHjWINTa/Ii2qyNU+D/eFrvNU0zhjDGryETEM3gQzptX0/LhTQfClbNeosQulAZ8Wg3fRyQUSGnbFx1J3dx4KlgutnyDI4uavx0dd/r3H032/+7QoQYoES/8u7aO1oRFd3Cf4lDMxG/oFqIyVIIz2WuV/LzbdvyiHJ+G22Wu66meO2j0YPTQAJCLwqWtd1Qn5+ZCdbRf/0BFKSnew6/zxnAojAC778UVEPIsPDCen0HwFwC33WTcATXRhqMpz9OuGOYy9cz9svd42U1o1x+Ds34jbu9Rti175ExieO4dvKTl7c+mxvdS57iFS5DjbJ1VwMjQh6fiyldOSV/4uAS5wvDnGr8QX1FlCFubIL976RqNPq/6MvQHzcN2wDkkn1bvipNDZT6CvMtz0sfvICQwsJbsQUHB3pzjpHY9HIWXpbqu0qxAQiv9brHiTtvhaDtehByDMAl6t6XrztIQ=
appveyor:
  secure:
    BINSTAR_TOKEN: 4409vQ23RVI1nrckG8t+6WSnILOOzPs7lmX2u8sdfP+psxnWZ7zp2h6Sk2nHtK3r
