channels:
  sources: [ramonaoptics, conda-forge, defaults]
  targets:
    - [ramonaoptics, main]

github:
  user_or_org: hmaarrfk

travis:
  secure:
    BINSTAR_TOKEN: JGzhQCiTR5nmHu3r4O/NLtWZ3BQNJanLTp/EaupLg4ezCchTXkTuk90fF3kxYK5LQSZPptakzZhfCAKXxwTs+VdeEIGwpFT+Mm7IhrldcIjSvu/95g0+ISfbbXezCBw2ObY2teG1lyRAt9WPjd/pkiQ9Clji3wwZT9d5KvXH5VJRInHi2E116dBfc1XPEW4mv7pkwnT+RfLD6JHiLTBhj6SBrWDV6VAtxcLS16Gz5y4aPzOxliFmzFEBNlNwbdNHVmmCA9FdlV65aUiWE8EAFDfEN5wwrH7KMP1MPVdV0nt+iGJvnFCEcAZm8cbstshsKBD21iNJU73lFcQlrjI81c7tUtp43VN+CozXZbQBwscWY1aIzyt6w4CrRFYaczNx8jjSVxd9zUCgtQHCCoc1z/8hOVP0qdZQo9utLOqLdlXdcACqYc+T8YoZftzOui58xL0IF71VbX8nL7jtIwiQrYViegQuMaeqgRGEk7qBF+EIswrhWz21Va6zldpt4RGUX3M7j7quEONx6O5SknJVn4PGmrz/Yut7jsHlH5jp8GFRQrYIyAqArIfNQwG7SYGh6D3oEewqH6eou1fvo7wMZi2R2AVZuzx6R+O2IsjfO6HboKke5DJWKiHKHDVPzZNvu2t4Wv8K7KGyE6Qavs79Yg5R4EUp/MhjS77og7IXaBk=
appveyor:
  secure:
    BINSTAR_TOKEN: 4409vQ23RVI1nrckG8t+6WSnILOOzPs7lmX2u8sdfP+psxnWZ7zp2h6Sk2nHtK3r
