channels:
  sources: [ramonaoptics, conda-forge, defaults]
  targets:
    - [ramonaoptics, main]

github:
  user_or_org: hmaarrfk

travis:
  secure:
    BINSTAR_TOKEN: ZPZ3SJKt/maKq9ldOXcw8iGvd29dOvFe4oDVKl5JBgnajsdhnUt9bjPmAAgSv8+nXkOIBN5VQQoKOM1vBjQxX39s1Mplucd9sXMZMtvgEKHsQeEiXKqAmVNkW2Dui/Z6Ofy/QX2Bhb+xbnDWjjpFJNIJARvjuH2QjiEV5SweYGLRA8PvsyWaBCOPPd/N9KwY/MBAIbwg37hpGJiIh6CKbiodoVFKcCMyTlhr+cOiLtWK7N9DDv1YzKTDlq0PFWeCOMUnX4JIxSoX2IULLEm48twpyLnXuGENADlmOzd+AldYNkq4fEidq1pI+bOMLzZsmdOIksA6GgzFLE3cmSe5lF4nRz7WFZAExrPP+him8FZQkkMNka98WpeMm+UcyPrhiB+mJcCvkaFhmHI49MWiXlL2QK9mJCHfzNP6KAPY/WY3vd1x0BpBtJu71n7rhebaNFm/dz1OKD6yRW35Mw97fmsCxzisnPCbDaN3h1Yf0qNg/GlERIcbScuDFzm79lEL06QtKJpVaSXQoJQxOW/fkvPY/5zCqbmmqVPFZf4pJpMnkA3QRl9HJXUX3zNe3eE2d2BrVYlOaaY12ny/PKwVtxghx30WZLCgh0ykH38Yqtl7DT73DeSkLdp8TcDM1d6czS5QtnKhd2eMG+L0cfryDr7w0n/zYbf4Z1pHjVd1JqU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
