channels:
  sources: [ramonaoptics, conda-forge, defaults]
  targets:
    - [ramonaoptics, main]

github:
  user_or_org: hmaarrfk

travis:
  secure:
    BINSTAR_TOKEN: F+e9Tc40ncx7ZnOcPn722nOav4h+pnk1kv5L5ajju48BosoqJbl/EMK9dgu2aCnRu0VRhqAnbKDhv9wiV8+u+UPfTnkM+ZccoFtTujg68LNIdI8Y2b7MYDjHYKlgmaiP4tjBHxPh6mC0bkz9gF1MAxT8KtiELQHb03D/9H7Qkf7lVyJHftr9wSLfzEPJu+v8T51mC2FL6J3A5R2TCFll9qdnacUm1eFRqF8jssO28TkM3mxAwPJSPJaA9S0wGJ7Bck8/CTrr14gB3fCqkb2Zug1te8QaqAtuLjI8WpCFB7b77qmRT34dmt8CdhYqyY+8KrIVq7PIKVx4wcn+0Y+bpfgKpm9VYdHCFaM1pPew8FC8rexT8dLORX1NScwXMAHM1HGrN5ZxR5HAX24frfh27GLIuv/OQRGhHBole0Usth8IyccQZSBMZvzpuVuQL6lXNXtYpBz2checO09912scMsswpVPMrs4Z+Ib3su2A6kBDhwxZjk7u1xZ2YZDC0aVflx0gvNbkeEeqfOxwDRbn++OL7Jak8u60xeVKUD35blLt7ZtDoBmOcEMKLHoJKWc0qLlLPIq3p+q+zEryZERZrYYk80Z1w2Lbsf1ki/a9nzdjrEhRhF69ATAurC8zUuJpdGxUSJ2KLwbLFuZTuqFoUM9WBwceKR9MOpjcNoGCW5k=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
